version: "3.9"
services:
  ml-serve:
    image: taraman12/solar-park-detection-ml-serve:latest
    environment:
      - DOCKERIZED=True
      - aws_access_key_id=${aws_access_key_id}
      - aws_secret_access_key=${aws_secret_access_key}
      - region_name=${region_name}
      - aws_s3_bucket=${BUCKET_NAME}
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    expose:
      - "8080"
      - "8081"
      - "8082"
    # limits the number of cpus the container can use
    # else on each thread (core) a model will be loaded
    cpus: 1.0

  preprocessing:
    image: taraman12/solar-park-detection-preprocessing:latest
    environment:
      - DOCKERIZED=True
      - aws_access_key_id=${aws_access_key_id}
      - aws_secret_access_key=${aws_secret_access_key}
      - region_name=${region_name}
      - aws_s3_bucket=${BUCKET_NAME}
      - COPERNICUS_API_USER=${COPERNICUS_API_USER}
      - COPERNICUS_API_SECRET=${COPERNICUS_API_SECRET}
      - COPERNICUS_API_URL=${COPERNICUS_API_URL}
    ports:
      - "5678:5678"
    expose:
      - "5678"

# networks:
#   default:
#       name: my-net
#       external: true
