[tool.poetry]
name = "solarpark-detection"
version = "0.1.0"
description = ""
authors = ["FabKoch <55655975+Taraman12@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "solarpark_detection"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
