"""Add name_on_aws

Revision ID: 34a2b4eb9563
Revises: 1e8e04211e95
Create Date: 2023-06-01 18:38:48.819915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a2b4eb9563'
down_revision = '1e8e04211e95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solarpark', sa.Column('name_in_aws', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solarpark', 'name_in_aws')
    # ### end Alembic commands ###
