"""added Relationships

Revision ID: b856fa57c717
Revises: 9c33465701fc
Create Date: 2023-10-27 16:14:52.905431

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "b856fa57c717"
down_revision = "9c33465701fc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(
        "solarparkobservation_solarpark_id_fkey",
        "solarparkobservation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "solarparkobservation",
        "solarpark",
        ["solarpark_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "solarparkobservation", type_="foreignkey")
    op.create_foreign_key(
        "solarparkobservation_solarpark_id_fkey",
        "solarparkobservation",
        "solarpark",
        ["solarpark_id"],
        ["id"],
    )
    # ### end Alembic commands ###
