"""Base Version

Revision ID: bba5f69bb1ae
Revises:
Create Date: 2023-05-28 12:14:59.027615

"""
import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry

# from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bba5f69bb1ae"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maillist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_maillist_id"), "maillist", ["id"], unique=False)
    op.create_geospatial_table(
        "solarpark",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name_of_model", sa.String(), nullable=True),
        sa.Column("size_in_sq_m", sa.Float(), nullable=True),
        sa.Column("peak_power", sa.Float(), nullable=True),
        sa.Column("date_of_data", sa.Date(), nullable=True),
        sa.Column("first_detection", sa.Date(), nullable=True),
        sa.Column("last_detection", sa.Date(), nullable=True),
        sa.Column("avg_confidence", sa.Float(), nullable=True),
        sa.Column("lat", sa.ARRAY(sa.Float()), nullable=True),
        sa.Column("lon", sa.ARRAY(sa.Float()), nullable=True),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="POLYGON",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_geospatial_index(
        "idx_solarpark_geom",
        "solarpark",
        ["geom"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(op.f("ix_solarpark_id"), "solarpark", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_solarpark_id"), table_name="solarpark")
    op.drop_geospatial_index(
        "idx_solarpark_geom",
        table_name="solarpark",
        postgresql_using="gist",
        column_name="geom",
    )
    op.drop_geospatial_table("solarpark")
    op.drop_index(op.f("ix_maillist_id"), table_name="maillist")
    op.drop_table("maillist")
    # ### end Alembic commands ###
