version: "3.9"
# can be renamed to docker-compose.cloud.yml
services:
  # db-postgis:
  #   image: postgis/postgis:15-3.3 # alt: postgres:15.3
  #   restart: always
  #   volumes:
  #     - data:/var/lib/postgres/data
  #   environment:
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_HOST=${POSTGRES_HOST}
  #     - POSTGRES_PORT=${POSTGRES_PORT}
  #     #- POSTGRES_INITDB_ARGS=--encoding=UTF8

  #   ports:
  #     - ${POSTGRES_PORT}:${POSTGRES_PORT}
  #   expose:
  #     - ${POSTGRES_PORT}

  db:
    image: postgis/postgis:16-3.4 # alt: postgres:15.3
    restart: always
    volumes:
      - data:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      #- POSTGRES_INITDB_ARGS=--encoding=UTF8

    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}

  api:
    image: taraman12/solar-park-detection-api:latest
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DOCKERIZED=true
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    expose:
      - "8000"

    volumes:
      - data:/var/lib/postgis/data
      - /var/run/docker.sock:/var/run/docker.sock
  # downloader:
  #   build:
  #     context: ./downloader
  #     dockerfile: downloader.dockerfile
  #   environment:
  #     - DOCKERIZED=true

  ml-serve:
    image: taraman12/solar-park-detection-ml-serve:latest
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    expose:
      - "8080"
      - "8081"
      - "8082"
    # limits the number of cpus the container can use
    # else on each thread (core) a model will be loaded
    cpus: 1.0

  preprocessing:
    image: taraman12/solar-park-detection-preprocessing:latest
    depends_on:
      - ml-serve
    environment:
      - DOCKERIZED=true
      - MAKE_TRAININGS_DATA=False
      - PRODUCTION=true
    ports:
      - "5678:5678"
    expose:
      - "5678"
    # prevents the container from being started automatically
    # when running `docker-compose up`
    profiles: [ "cli-only" ]

  frontend:
    image: taraman12/solar-park-detection-frontend:latest
    environment:
      - VITE_DOCKERIZED=true
      - VITE_GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - VITE_AWS_ACCESS_KEY_ID=${aws_access_key_id}
      - VITE_AWS_SECRET_ACCESS_KEY=${aws_secret_access_key}
      - VITE_BASE_IP=${VITE_BASE_IP}
    ports:
      - "80:5000"
    expose:
      - "80"

volumes:
  data:
