version: "3.9"
# can be renamed to docker-compose.cloud.yml
services:
  api:
    image: taraman12/solar-park-detection-api:latest
    ports:
      - "8000:8000"
    command: bash -c "cd /code && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --proxy-headers"
    environment:
      - DOCKERIZED=true
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - aws_access_key_id=${aws_access_key_id}
      - aws_secret_access_key=${aws_secret_access_key}
      - aws_s3_bucket=${aws_s3_bucket}
      - region_name=${region_name}
      - DOCKER_SWARM_MANAGER_IP=${DOCKER_SWARM_MANAGER_IP}
      - DOCKER_SWARM_JOIN_TOKEN_MANAGER=${DOCKER_SWARM_JOIN_TOKEN_MANAGER}
      - DOCKER_SWARM_JOIN_TOKEN_WORKER=${DOCKER_SWARM_JOIN_TOKEN_WORKER}
      - FIRST_SUPERUSER=${FIRST_SUPERUSER}
      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD}
      - ML_HOST=${ML_HOST}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    networks:
      - mynetwork
    volumes:
      - data:/var/lib/postgis/data
      - /var/run/docker.sock:/var/run/docker.sock

  new-frontend:
    image: taraman12/solar-park-detection-new-frontend:latest
    environment:
      - VITE_DOCKERIZED=true
      - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}
      - VITE_BASE_IP=${VITE_BASE_IP}
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
    attachable: true

volumes:
  data:
