name: Docker Build and Push

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker image
        # run: docker build -t my-dockerhub-username/my-repo:latest .
        run: docker build -t taraman12/solar-park-detection-downloader:latest -f src/downloader/downloader.dockerfile ./

      - name: Tag Docker image number version
        # run: docker tag my-dockerhub-username/my-repo:latest my-dockerhub-username/my-repo:1.0.0
        run: docker tag taraman12/solar-park-detection-downloader:latest taraman12/solar-park-detection-downloader:1.0.0

      - name: Tag Docker image latest
        # run: docker tag my-dockerhub-username/my-repo:latest my-dockerhub-username/my-repo:1.0.0
        run: docker tag taraman12/solar-park-detection-downloader:latest taraman12/solar-park-detection-downloader:latest

      - name: Push Docker image
        # run: docker push my-dockerhub-username/my-repo:latest && docker push my-dockerhub-username/my-repo:1.0.0
        run: docker push taraman12/solar-park-detection-downloader:latest && docker push taraman12/solar-park-detection-downloader:1.0.0